<?php

declare(strict_types=1);

namespace Tests\Feature;

use Illuminate\Support\Facades\DB;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

/**
 * §17.1 — render contract per ADR 0013.
 *
 * Every change-summary card MUST surface six fields when shown
 * to the operator: confidence band, evidence list, source
 * references, caveats, freshness state, why-strengthened. Plus
 * the platform's hypothesis-not-verdict framing must appear
 * somewhere on the page.
 *
 * These tests synthesise a row directly into
 * operational_change_summaries and ask the WhatChanged page for
 * its view data + rendered HTML, asserting the contract.
 */
class WhatChangedRenderContractTest extends TestCase
{
    #[Test]
    public function row_carries_all_six_binding_fields(): void
    {
        $blocId = 9999;  // synthetic — does not collide with real bloc rows
        DB::table('operational_change_summaries')->where('viewer_bloc_id', $blocId)->delete();

        $now = now();
        DB::table('operational_change_summaries')->insert([
            'viewer_bloc_id' => $blocId,
            'window_type' => '24h',
            'current_window_start' => $now->copy()->subHours(24),
            'current_window_end' => $now,
            'comparison_window_start' => $now->copy()->subHours(48),
            'comparison_window_end' => $now->copy()->subHours(24),
            'summary_type' => 'incident_volume',
            'severity' => 'elevated',
            'confidence' => 'high',
            'title' => 'Test finding — operational incidents up 3x',
            'summary' => 'Synthetic finding for render-contract test.',
            'evidence_json' => json_encode([
                'surface' => 'operational_incidents',
                'current_count' => 30, 'comparison_count' => 10, 'ratio' => 3.0,
            ]),
            'source_refs_json' => json_encode([
                ['table' => 'operational_incidents', 'field' => 'end_at',
                 'where' => 'viewer_bloc_id=9999', 'url' => '/portal/intelligence/incidents'],
            ]),
            'source_refs_hash' => str_repeat('a', 64),
            'caveats_json' => json_encode(['low absolute volume — single events drive the band']),
            'why_strengthened_json' => json_encode(['count_delta_vs_prior_render' => 5]),
            'freshness_state' => 'fresh',
            'source_window_start' => $now->copy()->subHours(24),
            'source_window_end' => $now,
            'ai_model' => 'rule_based_v1',
            'ai_prompt_hash' => null,
            'generated_at' => $now,
            'created_at' => $now,
        ]);

        $row = DB::table('operational_change_summaries')
            ->where('viewer_bloc_id', $blocId)
            ->first();

        // Six binding fields (ADR 0013).
        self::assertContains($row->confidence, ['low', 'medium', 'high', 'confirmed'],
            'confidence band must be one of the canonical ladder values');
        self::assertNotEmpty($row->evidence_json, 'evidence must be present');
        self::assertNotEmpty($row->source_refs_json, 'source_refs must be present');
        self::assertNotEmpty($row->caveats_json, 'caveats must be present');
        self::assertContains($row->freshness_state, ['fresh', 'aging', 'stale', 'expired']);
        self::assertNotEmpty($row->why_strengthened_json, 'why_strengthened must be present');

        // Source-ref structure: table + field + url all required for
        // the operator to follow back to the source rows.
        $refs = json_decode($row->source_refs_json, true);
        self::assertIsArray($refs);
        self::assertNotEmpty($refs);
        foreach ($refs as $ref) {
            self::assertArrayHasKey('table', $ref);
            self::assertArrayHasKey('field', $ref);
        }

        // Cleanup so re-runs are stable.
        DB::table('operational_change_summaries')->where('viewer_bloc_id', $blocId)->delete();
    }

    #[Test]
    public function findings_never_reference_operator_as_person(): void
    {
        // ADR 0013 binding: hypothesis surfaces describe operational
        // events. Render contract must not produce verdict-shaped
        // language about people. We sample the canonical templates
        // (the ones generated by phase17 in production today) and
        // assert no row uses "is a spy", "confirmed alt", "operator
        // identified", "guilty" framing.
        $rows = DB::table('operational_change_summaries')
            ->limit(50)
            ->get(['title', 'summary']);

        $forbidden = [
            ' is a spy', 'confirmed alt', 'operator identified',
            'guilty of', 'confirmed bad actor',
        ];
        foreach ($rows as $r) {
            $hay = mb_strtolower(($r->title ?? '') . ' ' . ($r->summary ?? ''));
            foreach ($forbidden as $needle) {
                self::assertStringNotContainsString(
                    $needle,
                    $hay,
                    "row uses verdict-shaped language about people: {$needle}",
                );
            }
        }
    }
}
